#lang racket/gui
(require ffi/unsafe ffi/cvector ffi/unsafe/cvector)
(require "assets.rkt")
(require racket/draw/unsafe/cairo)
(define img (load-image "ass/banana00000.png"))
(define h (send img get-handle))
(define d (bytes->immutable-bytes (cairo_image_surface_get_data h)))
(define (bytes->cvector b)
  (make-cvector* d _ubyte (bytes-length b)))
(define v (bytes->cvector d))
(define (g1 x y) (send img get-argb-pixels x y 1 1))
(define (g2 x y) x)
(displayln (g1 10 10))
;(displayln (cvector-ref v 0))